version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stock-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13gxrzou29u0v"
s3_prefix = "stock-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
