AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stock-analyzer

  SAM Template for stock-analyzer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AnalyzeStockFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: analyze_stock_function
      Handler: analyzer/app.lambda_handler
      Runtime: python3.8
      Events:
        Analyzer:
          Type: CloudWatchEvent # More info about CloudWatchEvent Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#cloudwatchevent
          Properties:
            Pattern:
              source:
                - aws.ec2
              detail-type:
                - EC2 Instance State-change Notification

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AnalyzeStockFunction:
    Description: "Analyzer Lambda Function ARN"
    Value: !GetAtt AnalyzeStockFunction.Arn
  AnalyzeStockFunctionIamRole:
    Description: "Implicit IAM Role created for Analyze Stock function"
    Value: !GetAtt AnalyzeStockFunctionRole.Arn
