AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for stock-analyzer

Globals:
  Function:
    Timeout: 3

Resources:
  AnalyzeStockFunction:
    Type: null
    # AWS::Serverless::Function
    Properties:
      CodeUri: null
      # analyze_stock_function
      Handler: null
      # analyzer/app.lambda_handler
      Runtime: null
      # python3.8
      Events:
        Analyzer:
          Type: null
          # CloudWatchEvent
          Properties:
            Pattern:
              source: null
              # - aws.ec2
              detail-type: null
              # - EC2 Instance State-change Notification

Outputs:
  AnalyzeStockFunction:
    Description: "Analyzer Lambda Function ARN"
    Value: null
    # !GetAtt AnalyzeStockFunction.Arn
  AnalyzeStockFunctionIamRole:
    Description: "Implicit IAM Role created for Analyze Stock function"
    Value: null
    # !GetAtt AnalyzeStockFunctionRole.Arn
