AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stock-analyzer

  SAM Template for stock-analyzer

Globals:
  Function:
    Timeout: 3

Resources:
  AnalyzeStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: analyze_stock_function
      Handler: analyzer/app.lambda_handler
      Runtime: python3.8
      Events:
        Analyzer:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.ec2
              detail-type:
                - EC2 Instance State-change Notification

Outputs:
  AnalyzeStockFunction:
    Description: "Analyzer Lambda Function ARN"
    Value: !GetAtt AnalyzeStockFunction.Arn
  AnalyzeStockFunctionIamRole:
    Description: "Implicit IAM Role created for Analyze Stock function"
    Value: !GetAtt AnalyzeStockFunctionRole.Arn
