name: Deploy Lambda Function

# TODO: uncomment this for testing your local branch
on:
  pull_request:
    branches:
      - master

#on:
#  push:
#    branches:
#      - master

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    env:
      LAMBDA_NAME: analyze_stocks
      PYTHON_VERSION: 3.x
      TF_VERSION: 0.15.0
      IAM_ROLE_ARN: arn:aws:iam::129254356074:role/pshynin-${{ env.LAMBDA_NAME }}-role
      IAM_POLICY_ARN: arn:aws:iam::129254356074:policy/pshynin-${{ env.LAMBDA_NAME }}-policy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

# TODO: delete if the one above works
#      - name: Authenticate with AWS
#        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region us-east-1

      - name: Build Lambda function ZIP file
        run: |
          cd lambda 
          zip -r ${{ env.LAMBDA_NAME }}.zip ${{ env.LAMBDA_NAME }}.py
          pwd
          ls -la

      - name: Import existing resources
        run: |
          cd terraform
          terraform import aws_iam_role.lambda_role ${{ IAM_ROLE_ARN }}
          terraform import aws_iam_policy.lambda_policy ${{ IAM_POLICY_ARN }}

      - name: Deploy Lambda function
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
