name: Deploy Lambda Function

on:
  # push:
  # uncomment the line bellow for testing with pull requests
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.x
      TF_VERSION: 0.15.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Lambda function ZIP file
        run: |
          cd lambda 
          zip -r analyze_stocks.zip analyze_stocks.py
          pwd
          ls -la

      - name: Deploy Lambda function
        run: |
          cd terraform
          terraform init
          terraform import aws_lambda_function.pshynin_analyze_stocks pshynin-analyze-stocks
          terraform import aws_iam_role.lambda_role pshynin-analyze-stocks-role
          terraform import aws_iam_policy.lambda_policy pshynin-analyze-stocks-policy
          terraform plan
          ls -la
          terraform state list
          terraform state show
          terraform state show aws_lambda_function.analyze_stocks
          terraform apply -auto-approve
