name: Deploy Lambda Function

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.x
      TF_VERSION: 1.5.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.0.0
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Lambda function ZIP file
        run: |
          cd lambda 
          zip -r analyze_stocks.zip analyze_stocks.py
          pwd
          ls -la

      - name: Verify Lambda function changes
        run: |
          cd terraform
          terraform init
          terraform import aws_iam_role.lambda_role pshynin-analyze-stocks-role
          terraform import aws_iam_policy.lambda_policy arn:aws:iam::129254356074:policy/pshynin-analyze-stocks-policy
          terraform import aws_iam_role_policy_attachment.lambda_policy_attachment pshynin-analyze-stocks-role/arn:aws:iam::129254356074:policy/pshynin-analyze-stocks-policy
          terraform import aws_lambda_function.pshynin_analyze_stocks pshynin-analyze-stocks
          terraform plan
          ls -la
